### ISSUE TITLE
undefined method `headers' for nil after upgrading to v1.0.0

### ISSUE THREAD

**Issue by Subtletree** [cortiz/prawn-rails#27]
I'm using prawn to render a pdf to string:

`ApplicationController.new.render_to_string("/template.pdf", locals: { model: self })`

template.pdf.prawn
```
require 'stringio'

@model = model if defined?(:model)

prawn_document(:page_layout => :portrait) do |pdf|
  ...
end
```

This works perfectly with `prawn-rails v0.1.1`.

After upgrading to v1.0.0 I get the following error:
`ActionView::Template::Error: undefined method 'headers' for nil:NilClass`

The error supposedly occurs on line 3 of the above template. However If I remove the line the error still happens on line 3. Also If I add a `byebug` to the top of the template file the breakpoint is never reached as the error happens before. 

Appreciate any advice on this, cheers!

Update: looks like this change could be the culprit
https://github.com/cortiz/prawn-rails/pull/16/files

**Comment by westonganger** [comment]
Good eye. Yes I think I will work around this by checking if `controller.response` is not nil for the cases where render_to_string is used.

**Comment by westonganger** [comment]
I have just pushed changes for this to master. Would you mind testing master on your project to see if its working. Also would love a PR for a test case for this if you are savvy.

**Comment by Subtletree** [comment]
1.0.1 working perfectly 😀  thanks!

Will look at adding a test case some time this week.

**Comment by westonganger** [comment]
Any chance to look at this yet? Would love to release a tested new version to rubygems.

**Comment by westonganger** [comment]
I have now added the test case for this and released v1.0.1 to rubygems.
